sudo: required
services:
  - docker

before_install:
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml up

script:
  - docker build -t payment/api-gateway -f Dockerfile.heroku .
  - docker run -d payment/api-gateway

after_script:
  - docker-compose down

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: api-gateway-payment
  on:
    repo: ericjrsilva/api-gateway